#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dirac import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = ' Energy eigenvalues in atomic units',
      to_re       = 'Relative real eigenvalues in other units;',
      rel_tolerance = 1.0e-5)

test.run(['eom_ip.inp', 'eom_ea.inp', 'eom_ip_dc_sym.inp', 'eom_ip_dc_nosym.inp', 'eom_ip_dc_sym_overlap.inp', 'eom_ip_dc_nosym_overlap.inp', 'eom_ee_dc_sym_overlap.inp', 'eom_ee_dc_sym.inp'], ['h2o.xyz'], f, args='--mw=110')
test.run(['eom_ip_linear.inp', 'eom_ea_linear.inp','eom_ee_linear_0g.inp'], ['f2.xyz'], f, args='--mw=110')

sys.exit(test.return_code)
